name: corevend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: 1.3.0 
  path_provider: ^2.0.0
  crypto: ^3.0.6
  barcode_scan2: ^4.5.1  # Vercao mais reecente
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true